# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

FROM phusion/baseimage

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
  && curl -sL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
  && apt-get update \
  && apt-get install -y \
    curl \
    fabric \
    git-core \
    google-chrome-stable \
    graphviz \
    libfontconfig \
    make \
    mysql-client \
    nodejs \
    python-imaging \
    python-mysqldb \
    python-pip \
    python-pycurl \
    python-virtualenv \
    unzip \
    vim \
    wget \
    zip \
    pv \
  && rm -rf /var/lib/apt/lists/*
