version: "2.2"
services:
  dev:
    extends:
      service: dev
      file: common-services.yml
    depends_on:
      - db
    networks:
      - network_1
      - selenium
  db:
    extends:
      service: db
      file: common-services.yml
    networks:
      - network_1
  dev_destructive:
    extends:
      service: dev
      file: common-services.yml
    depends_on:
      - db_destructive
    networks:
      - network_2
      - selenium
  db_destructive:
    extends:
      service: db
      file: common-services.yml
    networks:
      network_2:
        aliases:
          - db
  selenium:
    build:
      context: .
      dockerfile: Dockerfile-selenium
    volumes:
     - "./test/selenium:/selenium"
    depends_on:
      - dev
      - dev_destructive
      - chrome
    networks:
      - selenium
    environment:
     - "TZ=America/Los_Angeles"
     - PYTHONDONTWRITEBYTECODE=true
     - PYTHONPATH=/selenium/src
     - SCREEN_WIDTH=1440
     - SCREEN_HEIGHT=900
  chrome:
    image: selenium/node-chrome:3.11.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - selenium
    scale: 4
  hub:
    image: selenium/hub:3.11.0
    networks:
      - selenium
    expose:
      - "4444"
networks:
  network_1:
  network_2:
  selenium:
